language: python
sudo: required 
python:
  - "2.7"
  # - "3.6"

services:
  - docker

before_install:
  - docker pull alephdata/test-base
  - docker build --cache-from alephdata/test-base
  - docker ps -a

# command to run tests, e.g. python setup.py test
# script: make lint coverage
script:
  - docker run alephdata/test-base /bin/bash -c "cd /srv; nosetests -v --with-coverage --cover-package=ingestors;"
#   - nosetests -v --with-coverage --cover-package=ingestors

# after_success:
#   - coveralls
